package org.ij2art;

/** Storage slots for saved original implementations. These declarations are never
 *  called through this class: the payload overwrites each method's ArtMethod storage
 *  with a copy of a hooked target (ArtMethod.CopyFrom under STW), then creates fresh
 *  reflected Methods for the copies. Keep them public static and unsynchronized. */
public final class Backup {
    private Backup() {}

    public static void s0() {}
    public static void s1() {}
    public static void s2() {}
    public static void s3() {}
    public static void s4() {}
    public static void s5() {}
    public static void s6() {}
    public static void s7() {}
    public static void s8() {}
    public static void s9() {}
    public static void s10() {}
    public static void s11() {}
    public static void s12() {}
    public static void s13() {}
    public static void s14() {}
    public static void s15() {}
    public static void s16() {}
    public static void s17() {}
    public static void s18() {}
    public static void s19() {}
    public static void s20() {}
    public static void s21() {}
    public static void s22() {}
    public static void s23() {}
    public static void s24() {}
    public static void s25() {}
    public static void s26() {}
    public static void s27() {}
    public static void s28() {}
    public static void s29() {}
    public static void s30() {}
    public static void s31() {}
    public static void s32() {}
    public static void s33() {}
    public static void s34() {}
    public static void s35() {}
    public static void s36() {}
    public static void s37() {}
    public static void s38() {}
    public static void s39() {}
    public static void s40() {}
    public static void s41() {}
    public static void s42() {}
    public static void s43() {}
    public static void s44() {}
    public static void s45() {}
    public static void s46() {}
    public static void s47() {}
    public static void s48() {}
    public static void s49() {}
    public static void s50() {}
    public static void s51() {}
    public static void s52() {}
    public static void s53() {}
    public static void s54() {}
    public static void s55() {}
    public static void s56() {}
    public static void s57() {}
    public static void s58() {}
    public static void s59() {}
    public static void s60() {}
    public static void s61() {}
    public static void s62() {}
    public static void s63() {}
    public static void s64() {}
    public static void s65() {}
    public static void s66() {}
    public static void s67() {}
    public static void s68() {}
    public static void s69() {}
    public static void s70() {}
    public static void s71() {}
    public static void s72() {}
    public static void s73() {}
    public static void s74() {}
    public static void s75() {}
    public static void s76() {}
    public static void s77() {}
    public static void s78() {}
    public static void s79() {}
    public static void s80() {}
    public static void s81() {}
    public static void s82() {}
    public static void s83() {}
    public static void s84() {}
    public static void s85() {}
    public static void s86() {}
    public static void s87() {}
    public static void s88() {}
    public static void s89() {}
    public static void s90() {}
    public static void s91() {}
    public static void s92() {}
    public static void s93() {}
    public static void s94() {}
    public static void s95() {}
    public static void s96() {}
    public static void s97() {}
    public static void s98() {}
    public static void s99() {}
    public static void s100() {}
    public static void s101() {}
    public static void s102() {}
    public static void s103() {}
    public static void s104() {}
    public static void s105() {}
    public static void s106() {}
    public static void s107() {}
    public static void s108() {}
    public static void s109() {}
    public static void s110() {}
    public static void s111() {}
    public static void s112() {}
    public static void s113() {}
    public static void s114() {}
    public static void s115() {}
    public static void s116() {}
    public static void s117() {}
    public static void s118() {}
    public static void s119() {}
    public static void s120() {}
    public static void s121() {}
    public static void s122() {}
    public static void s123() {}
    public static void s124() {}
    public static void s125() {}
    public static void s126() {}
    public static void s127() {}
}
