#!/usr/bin/env python3
"""Scaffold and compile ij2art ART-hook replacement DEX projects.

The ij2art CLI runs on the Android device, but a replacement DEX must be compiled
on a host with a JDK (javac/jar) and the Android SDK (platform android.jar and
build-tools d8). This script owns that toolchain so an agent never has to
assemble the javac/d8 command lines by hand:

  init   create src/<package>/<Class>.java with the HookContext contract
         documented in comments, plus hookproj.json
  build  compile every src/**/*.java into a standalone replacement DEX and
         print the exact ctl commands to upload and install it

Toolchain resolution order (first hit wins):
  JDK:        --jdk DIR | JAVA_HOME | javac/jar on PATH
  SDK:        --sdk DIR | ANDROID_HOME / ANDROID_SDK_ROOT | ~/Library/Android/sdk,
              ~/Android/sdk, ~/android-sdk (first with a platforms/ dir)
  build-tools:--build-tools DIR | highest version under <sdk>/build-tools
  platform:   --platform android-36 | --platform /path/android.jar | highest
              version under <sdk>/platforms
  hook API:   --hook-api JAR | <repo>/out/ij2art-hook-api.jar | ij2art-hook-api.jar
              next to this script | ./ij2art-hook-api.jar | the embedded copy
              (build.sh keeps it inside this file, so the script is self-contained)

Exit codes mirror the ij2art CLI: 0 success, 1 runtime error, 2 usage error.
"""
import argparse
import base64
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST = 'hookproj.json'
SIGNATURE = '(Lorg/ij2art/HookContext;)Ljava/lang/Object;'
CLASS_RE = re.compile(r'^[A-Za-z_$][\w$]*(\.[A-Za-z_$][\w$]*)+$')
METHOD_RE = re.compile(r'^[A-Za-z_$][\w$]*$')

# BEGIN_EMBEDDED_HOOK_API_JAR (generated by build.sh; do not edit)
_EMBEDDED_HOOK_API_JAR_SHA256 = 'a221bd2708d8865e0b94274278ba3b920854653abfc0a90c0d677392302abaac'
_EMBEDDED_HOOK_API_JAR_B64 = (
    'UEsDBBQACAgIAJK6MV0AAAAAAAAAAAAAAAAJAAQATUVUQS1JTkYv/soAAAMAUEsHCAAAAAACAAAA'
    'AAAAAFBLAwQUAAgICACSujFdAAAAAAAAAAAAAAAAFAAAAE1FVEEtSU5GL01BTklGRVNULk1G803M'
    'y0xLLS7RDUstKs7Mz7NSMNQz4OVyLkpNLElN0XWqBAqY6xnoGZoqaHjk56YmFaWWa/Jy8XIBAFBL'
    'Bwg4qwX9OgAAADkAAABQSwMECgAACAAAYBAxXQAAAAAAAAAAAAAAAAQAAABvcmcvUEsDBAoAAAgA'
    'AGAQMV0AAAAAAAAAAAAAAAALAAAAb3JnL2lqMmFydC9QSwMEFAAICAgAkroxXQAAAAAAAAAAAAAA'
    'ABcAAABvcmcvaWoyYXJ0L0JhY2t1cC5jbGFzc4WTV1dTaRSGvyCCAyhgR8VeAJVwvtMVUUGxIagg'
    '9hJCxIRqKPaC3Sk/Zq5mrbmYHzA/ata85/3Wmpu5eHOxd5LneXZucv7+58+/jDGB+a3B1Jg19aa2'
    'yaw1dTnTUimsFPIzhbmp/MhEpVRcypm63vJceakvZ9Z0dI7Xm3U50zpfncqXK7ZQXcr3F4rTyws5'
    'UzswP1nKmeah8lxpeHl2olQdK0zM4JuaxZ5seNmw2fCzEWQjzEaUjTgbSTZS/M6i18PpcVpOnzPg'
    'DDkjzpgz4WRr2Vq2lq1la9latpatZWvZWrY+W5+tz9Zn67P12fpsfbY+W59twDZgG7AN2AZsA7YB'
    '24BtwDZgG7IN2YZsQ7Yh25BtyDZkG7IN2UZsI7YR24htxDZiG7GN2EZsI7Yx25htzDZmG7ON2cZs'
    'Y7Yx25htwjZhm7BN2CZsE7YJ24RtwjZhm7JN2aZsU7Yp25RtyjZlm7JN0dbiv9HjlueWdct3K3Ar'
    'dCtyK3Yrcctd8dwVz13x3BXPXfHcFc9d8dwVz13x3BXPXbHuinVXrLti3RXrrlh3xbor2X+uYXR+'
    'uVosDZazx6PRPUDd2XNnPFOPxzF7rWLjgTQ58xM+tWPnsNd2/WFyv+MNjmDW8ct1UBr/U9uMe/1P'
    'awBu0loj8HqtNQFv0Np64GatbQBu0VozcKvWWoA3aq0VeJPWNgJv1tom4C1a2wy8VWtbgLdpbSvw'
    'dq1tA27T2nbgHVprA96ptR3Au7S2E7hda7uAd2utHXiP1nYD79XaHuB9WtsLvF9r+4APaG0/8EGt'
    'HQA+pLWDwIe1dgj4iNYOA3do7Qhwp9Y6gLu01gl8VGtdwMe0dhT4uNaOAXdr7ThwXmvdwD1aywN7'
    'WusBtlrzgH2tWeBAaz5wqLUAONJaCBxrLQJOtBYDp1pLgE9oLQU+qbUTwL1aOwl8Smu9wH1aOwV8'
    'Wmt9wGe0dhr4rNbOAPdr7SzwgNb6gc9pbQD4vNbOAQ9q7TzwBa0NAl/U2gXgS1q7CHxZa5eAr2jt'
    'MvCQ1q4AX9XaEPCw1q4Cj2htGPia1kaAr2vtGvANrV0HHtXaDeAxrY0C39TaGPC41m4C39LaOPBt'
    'rd0CvqO128B3tXYH+J7W7gLf19o94Adauw/8UGsPgB9p7SHwY609Ai5o7THwhNYKwEWtTQBPaq0I'
    'XNLaJPATrZWAp7T2BPip1qaAy1p7ClzRWhl4WmsV4BmtTQPPam0GeE5rs8DzWpsDXtDaPPAzrS0A'
    'V7X2DHhRa1XgJa0tAi9rbQl4RWvLwM+1tgL8QmvPgV9q7QXwK629BH6ttVfAb7T2Gvit1t4Av9Pa'
    'W+D3WnsH/EFr74FXtfYB+KPWVoE/ae0j8GetfQL+orXPwF+19gX4m9a+An/X2jfgH1r7Dvyz1n5g'
    '/oJdY379F1BLBwgT3TN/JgQAAFcXAABQSwMEFAAICAgAkroxXQAAAAAAAAAAAAAAACAAAABvcmcv'
    'aWoyYXJ0L0JyaWRnZSRDYWxsUGxhbi5jbGFzc31V3XMTVRT/3aZ0k2XT0pRKrQ0GqJgmhZaIX7QU'
    '2lKkSqEQBFtQ2W4uYctmN+5uSvHriRd88kkH/EBxhqqDX4xJGRmrvsCM/4f/gI+MI557N22ZpOPD'
    '7t5z7jm/e+7vfOyf//6yBGA33lPRgJCCRg3r0MSwYVaf0/ss3c73HZ2Z5YbP0DRo2qY/xBBK9pxU'
    'EUZEgaphPTSGrlVzl5+zyL5vbJ4bJV+fsTiDluf+hJMzz5nc9STAuIpmtCjYoKEVMYbOeoBlB4aw'
    '6WV93TcNhsbkeM90BBvRruAx4buJfB0332fOZnTX7xtxzVyed4/qljVJaAxsWoT6uIZOPMHQSoEc'
    '4Ialu6adH7V0j6JpS/YcXj1dKgfECXENm/EkQyS37ED+dZYCfYuGrdgWoE/qrl7gPndPXCpyQt+Y'
    '7Dm9JvxTGrbjaYJ39YvSiYxj9aYKehhaarTCP62hV/ivn3HmeS5AULETfQr6NexChuKpI4ZB1Q2D'
    'e153f38/Q3ey7rx6LhTsZojX52fUsT3fLRm+40bwHJ5X8IKGFwVjzavGJx0zR1k7MTU5pmCAoWON'
    'PHP/vJNTsQd7NQyJLEWJx+PcL7m2IFFcdr+GYZkLIus490qWL7SjGg4IbUBBoFeRxEENL+EQg0I4'
    'RygbMguP3Cvri2zKLLys4RUcJlpc6R1Yx+ptFRxh2LqqHrcsntetYTdfKnDbH5s3eNE3HTuMSYZt'
    'nqzWREHeLOFyg5tz3E0USp6fmOEJu2RZKiZwXDRblqE9WX+gaLEkXtVwEqcoPNMbJ7Z12+A15kF3'
    'DvRMhzHFsMm053TLzNUeHcZp2tSr0SYMp0TvgukVdN84Lw56XcMbeJOoNL1J1yyYPnnJRp1WoJNr'
    'bXwjJdPKcVfFWYTCoBR3roD7lLMV7ITuJ4TROQ15nKchoheL3Cb7HWvduU5VPWZAQMwKiAs0a2gE'
    '/K9hQYMt0h/2nWCT6iZr5m2dKkrUQm2FD6aGqDLb63ov0G95NND64UaJovoedXKE3HLYtPmRUmGG'
    'uj8YfFGaW8aFCb1YlcMyO7pPy+QaWTy9RmIJXhE9W/RpQKhZp+Qa/KApwNYHPb1T+NCMHbdt7srA'
    'xdwJL49A9FOZN9CQp2Er5iWtNojBBgaH1g0okkyTaEV+i+TeGnm4xv5AjUw9ROsQPevg0o4HsCga'
    'peaD1CJYKl2BcgfRMtrEsqOMLvFNlNGdSv2M7qVfkSwjFdrbJaUb6KBvSgpdmTvYkb3cwBYe/pVK'
    '/4FnriJyG88uQE3/jj0VDJaxT2DsI+XN5S0hk1sZI3KrgrEyxn+S8fr0TkGl9zWK8BO04FNi5TO6'
    '0edI4zrd5QsY+BLv4wau4CuUyHIYTQ+xQ/wgNyoIM+AB4hMkPEQTGgJl9ZvMrq0mkDlcDKjB33Rw'
    'I30/ptjarqI1fQ/b72JiKnZ0Ecd+I6mZNrqInxPXEJUbr4mN3nuI9i5Jgq5X9dNCHxqKV1k71BvP'
    '3EdMSPFMBWeuon9Biql4pldoCHCzcLyLs1OLmIkZFfB4BWYFlkC6HCKWy6s8ZaDR+ybVzgL96L9G'
    'O75BN76l38wtDOI7HMT3OIYfiKMf8SGtP8JtyVcr1PbmSDTyDxiLN3c+oLIA5nGqen+d4EVJ7lpJ'
    'WzR9H0rjAhpDt2jVFuTszLVlHckjgo5bK5E1y9oqU21XiNxFeaqKpth++u3RQ1aXpO3beEfuUN9T'
    '1O+i4z9QSwcIQ806iwgFAADzCAAAUEsDBBQACAgIAJK6MV0AAAAAAAAAAAAAAAAXAAAAb3JnL2lq'
    'MmFydC9CcmlkZ2UuY2xhc3OtWAl4W1eV/q8l+z3Jz44rx0mU2qmyNJXlLVudxnEW24kbt44T4kwy'
    'jru9SC/2S2Q9V+8pdWAKHShlK1AYBkhSaNgahmFmTCmK29AmZRtapgxLp2U2ZmE2OgyzQmHGIfPf'
    'pyfLspWQ7wN/35Wu7j333HPP+c9/7vULv3j6WQAbxK1BlMGnwK+hHBUC11npkTbz6Do97bR1p83E'
    'iCFQftiaMBICq6L9R/XjeltST4209SR1297cOG8kCBUBBUENldAEagrzew4fNeKOQEWnmTKdrQK+'
    'aOOBIKqxQEGNhusQKhIfdNJmaoTiSSM14oy64n0KFgqsKAj1JZPGiJ7sSo9kxoyUs3Mibow7ppVS'
    'sUhg8Zhp29QRSRh2PG2OO1Y64pwYN4KoxRJpX1igbvaZcltuzll1vYZ6NHD/+Kie7qLd/mhfY08A'
    'NyCiYLmGFVgpUF1YfMAy6SP//qG9O+nGeX4J4Ea5cDXnClPdlpU09FQAUTnXWKSv+4RjBNAkJ5oF'
    'amfpoz163DHSAbTK2TaBBbPOMGqlnQDWypl1RZv1pRxjRK7aIOduLtqs30qNBLBRTtxSpK43aelU'
    '1yFnNhfFZ4eVOZw0pKe2aNiKbQKKmUoYE3uOEDHRvr7GPjnXpaEbPQIBO3PY9iK6SM7Od7sU3ylV'
    '9eZ83adil0DYTB3Xk2YiYrnwmRVLKX+bhtvRz63TxnhSjxtSeU9PSeUD2KNgr4bXYV/RCd3wUMMR'
    'Kz2gj1HDlhKQODQ3nv2WnjDSJfFfhv0afgMHeAqJNoFtJRQO911B46H5KhX8JsE8V0V3xkxyQRAH'
    'EVAxzJPnPTUL7roTkQJ3argLdxPL+vi4kSJMW0rBft6Qt8VmqUKXKg4L1EdLxG62YEKDAWJAdax8'
    'Ci+MXiHcoxpMiZxKntPpy6FHxTGB5cbEOKNtJCJx6YLWMcMZtRJRPT1iN6YNJ5Nmho8JiE6pxdIw'
    'jnsFgrZD2rIPmpItSib2IRWVcoWjIYPj9Idxb0ZP2nOkc0TlSk8IdLoWRCRnmXTv6420HdFTxKMz'
    'aqQjNs3kcCRnIGfSRiSTsjPj40xDI6Hg9fnczThmsq0rndZP9Ju2E8QJBCpxP96o4E0aHpDWVBfk'
    'pAgZT08kpMybNbxFsqPf5vYq3kqVjmVFxvTUicg4yYCb0yoVb2Oe5TmvUcU7pFxaN5PFHKjiXXRw'
    '3EoxHzNxiZKcR11ujIxlbCdy2IgckBu/W8N78F4mh2O5lgtEo8MlPFViTMH7BELDJfJjAL+j4QP4'
    'XSJ2xHB2GPRv2kj0FOwRWB+dv3A2hNLGkSQ3aZu1yFX8IQ0fxkmy3izFu93ICGwvlYXXtEtOAzc4'
    'jUcVfETDR/GYwJIrCQpUcft9rk/3uwRQG52f1Co+xsQo8rxpj+lOfFTu8wkNn5QR16hpt5Uwj5gM'
    'cBCP46yCT2v4PXxGYGkJAzxR5oJpd0nC1eNe5Tok1X5Wwx/gD5mbpp0v7qyqxPmkQJPuybvoPuxO'
    'XwnWkuSe0PB5POlSr20lj1NV37z7gcdpV+eavPE7J4x4xtFZVOjqLM4pmNLwlHR1/dWEZ0ebqt19'
    'JRbOa/ii5CGFs5LYFTwr0HBVDKm4SPrPmRiZlSB2JGMbka59+yO5uV5djp5wHTXHMyq+lLtEteYu'
    'Ua05P6v4CuE+a3iXZR3jzo4x4aj42pwlevxYZlzF1wVio5ST1pBsInJNZHDH7RHTsY3kkYhpz43J'
    'Cxq+IWNS5cVkPwnTcOTMixq+iT8lx3gzu2h7UgJl568WNC83VHxboM0rwvImNsMjuoeh5kjKIrRm'
    'u1Xi+bsaXpJgJiIHdMc8Tk+9LLD2Cpr0lD7CmhBNWamWlCve6KmX6D4nw/7nGv4Cf8mD8uCzjsOL'
    'xPwk9E6q4q8Fmmdv6TmJJJ9xbDNhRKSXk6Yha+vE3WZCWv43Gv7Ws3zQoS1xOfj3Gn7gDe7l9ciM'
    'q/hHkm2p44y78xHbW3sa/6zhX/DDHJz35lldEojtVtD5XKXgX3Ogyl/Yi0D1b6S8UvvmNozkaNrz'
    'XrQ0MhsDRM6/a/gP/CfvdHv7uwYGWQH6C2WKwYxn0mmql2nkdXfp9uhufZxJvAH/reF/8BMmIW8m'
    'GUNeDWujt82Og7x4UvI1/EzBzzX8L/5PYPW1bUDuoqcoXqp2lypIl8iZ8543q3r0ZHIvBYOYxmW+'
    'CnirwPLo1flJvhBeE2Wa8Ak/by/jGafvCOmWtgncUsKcazKQaSoqNKEIlf5i3FK9shRuid72S2zp'
    'v/KZqHNaBDVRKfgUU93boe4YsorP375UXecxXxXV0ikLBOK/zJJr0nk1a+V+p8V1mgiJWl7OeJ+1'
    'jtHaTddobYmYizoWtvlG91FzXJcPxRxDzrwbg2KhWKyJJYJPQ1UyiE7m5+W7iDv2j6at+7w6NS2u'
    '10S9vL0pelwqsRWxrKhiubnaw/tt4XEqInzEzuGbTJJvG8uwXZp07wGRALWv0MRKsYr1PCeSe6GE'
    'StymRQOWyGjdpImofHiXx5OWbcjMCvBWOGiOkC8zaS4+cI352zk3S68Wua18G/p7rAT1L+g3U8ZA'
    'ZuwwyStXn6vIj/FjVOn9Ds54gs5aKxCZ46wBy+m1MqnEjJhA96/2hOqMbSUWNgiUDfcpor3oOT1r'
    'l5DH+/sKoRGwr6FAXr1ulqikw1fPJD60C++NHER5F5hniDxWybMSvAnTHpcoEkj/evL2irW/ZN5t'
    'pY9LvQrE9iLnz6QSUSHzx7ZXrVmzhubz1eX9lyg4aGXScaPXlEKVOeC1Sg28HfelUkbaPbUskmoe'
    'jljLuqUCZPKlsnhBiBh/lYkmaJyp5KcQzRxpgGR7oDx2Dsrn5ALRws8Kd7AaQfmMh0+KlkU5SpXi'
    'oSZfa7u/zh/LoupjqDqP2qFQ3TksvhBr8t3ROuy/Z08WS9vL68o/A/knuvkh2zDbg2xvZ3vUG/9w'
    '7tvtP8L2Aa9/pjA+t+HhWf2JOXMPsP2k4SSefwLLJp/AKrab2GJsLWxr2NaztbNtmozVbOZRsuhs'
    'r6irYO8TqDiL9/IUrXUVWWzvUMJKDad3PIoq9obZO+0d91Z53CZfXQUPy6k2Kdbna57C7kmulo75'
    'OMIxV/nSmuEzqJKeoezZyz+Q2v2J63D5k3K35bGmZt8UBg/G6vyu+PYiZXKz8zg4dA5DoUNZ3FHn'
    'z+KeLOJyezecMlZHEOZnCOXyn3pYiNWoo/8W4dNYjM9yZJLzTxIGU7ie74F6XGTQv4Jl+Doi+C6W'
    '4/tYgR9iJS5hlVBwo6jGalJpo9iCmOhHk9iPZnEUa0Qrd1mF0DSWiGk+tBWf9zeNOg4sU1Ad+Dnq'
    'bqhuEG2U9BNJazzQrUNAvpTYkziqp6WVjNexppoofbqlqaa1PouRrfWnUd3wUQQb/PfUn/EcfTTn'
    '6AY6xhejRzr8TXJaRqc8XB5KZpE6icXspbOwT3mL7pOL/F8MDvnq6fOOivM4QQ++gfGs8LU2ucHZ'
    '2CT7MjqNjyEWVvgzJuPwFH6rDAfDylP4bV5DGaTL33RVPihV5pfnQf+QN+iGVmrwU0OHmhd7zBN7'
    'uyuWM/EkGsMqsfkpb+6d7pw/rPiewcBTeLiM0Xkki/dPcqx87ugHOwLhQBanwmp++Rl3Occ+3h6s'
    'C07hU6dQKX/+/klP4I9yApMzYDlKIIDXUgU3YwHaCYONiOIW/tqEbejAIDbjTnRiFFtwL7biHRw9'
    'ie0EUTe+ih68iB14BTvxI/Tip7hVyP9Q1uM2sR63i1vRLwawW9yFATGK17mAaYN2CcuECFzCBgUD'
    'BMkl1CpivYL7ty6cxmqOXV87jZiC09NYJAIz2LmZmPlGHjP4IHwcBfbEmqbwud3NWXwhi6cHmp/D'
    'MyexSP4MVT/unfmCPHNL6DkXEXUtoS+7Ha0l9FU3ADmhP5ZCzQW/rHDZcogUd4i0N0y/3EG/3Ekv'
    '3MVT343duMc9TxV8lxBVkOVJlhZZKzaKWzxrbybCy/kdjjGLn+/wlz+D7JAv7B8c8je1TOFPBidn'
    'iFa+TGUKKxgpOjqfqp6yn/HoUtl7vKM/h9N5oH/LPcRFnB5oIQSm8J386f7MdUEWr2TxvVgeLH/l'
    'DVLw+xTM9f4ur+sfvNl/6vDz81RIfRy1Yf+z/jPQwn7futCreTU/cgULnuugv4AkPTdG76RIOhZJ'
    'Zpw0dC/WIE082cSLQ99mEMdxmLgPbyZxP4wTrkeXQJnGYnqUxEIULKwNuGTySLFzNwl4/lhPf0if'
    '1ZJmv9DPRHvaz4/vkRwOFupXNYWAN9JxbyIzPlBgJDq8nKbmVJ2iIlnn9sVYKh5HRejGSfZukr2o'
    '7MVkr0n2WmSvVfbWyN5a2Vsvextkr132NsreJtnrmIwV3LOawQTewn0fJDe/lcB6iMB6G9axDnYy'
    'vXrxTuzFu1xXBKEGA7k/jzk7oMrnkFesT3hQ2PQEfrxsCv+VxU8vYnqg5Wsob2GtmB5qPodfdPi9'
    '2bA/K4Q3r7ScRXnYXzBrkavoAh11kWY9R7O+hFZ82TUjBHL6QgXT01jOzy42RmCz6My5TaxkrlRK'
    '9y6ridzfPCXKOyrCFS1yu8B5vDq0rJn9cMU5UUXGLRf+Z6AS/MpgVtR0qGdR6bKYWETmDKtZsfQU'
    'Vp4XDfkyVytuYJ0LVzwplvNbljpx44WwyjVKVqwmk3UEc73gBTpjBdHQLhbyO0mEge24+5074zre'
    'coDn6dYXeKYXKfUtyn+brPYd7GLpG8VLXPcycfoSV72MN+AV9/w98F8mNSp+N81VRWwhLukEBa+C'
    '0SBtKRxuvEwnXElm2wzittWookvep+Zct6YgCiyQu25VMdjdMzezlS7KgcrzeG3onGj8PH489352'
    'ngftcY+7Q+x08SMYqjLRiyX/D1BLBwj6idSJQg4AAN8cAABQSwMEFAAICAgAkroxXQAAAAAAAAAA'
    'AAAAABwAAABvcmcvaWoyYXJ0L0hvb2tDb250ZXh0LmNsYXNzjVRZU9tWFP4uNpZx5ASTkLJjaBZb'
    'BJwGugSTpVBSIAaSmNIC3YR8YwRGYmSZ8NqfkR/Q6WsyE0OmnWnSp8707/S96ScZsMEuzYN07j33'
    'bN/Z/vrn198BjGEjgiYEFARVNCMk0Lqp7+qpgm7lU4vrm9JwBUITpmW6dwUCieRyC8JoURBRcQ6q'
    'wGXbyafMzVu646ZmbHtryrZcuecp6YZr7koBseqpnFdxAa0Cza69JS1y5zxum4qLuCQQkXvSKLn6'
    'eoEKfZlqCI58WmAMqenj97SCywId9SLz0t2wc57VDhWd6GII2z5LoKuBxYo4rfUI9NY/E0fRdUqG'
    'azueyT4V/YgLnDOqfIH+BnZrFNOe5qCKD3GFEN0Ns3iU0bbM6Sz7stdUXEdCIKg7+aLAxbXGYpqK'
    'Idyg2A5fBHoyNTWYdMxcXl6Z0guFR3xNRzCClIKbKj7CrRPVXdpwpM7kRI2S40jLPbpfSiQzp6V8'
    't2MqPsYnLKH9zJLOSRCHYhGKfabiNsYFVIMxLDpm3rT0gsD1RAM0yXqWggkmtsqeLRRkXi9kXd2V'
    '03uG3HFN2wqD3Tha029xsxiXezumI3Nx24mvy4Jt5Ytx147rlu1uSCfu+hFGkMZ9r9M/F2hP1HjP'
    'uo5p5dPJZQVTbMHqw0KJmbRNenFq3E8LtLBIpW0mrhjBJO5HMINZBQkVc3jIJBmMQJ7O5iHGCOax'
    'oGBRxSM8Znv+d/0Ewrt6wcwRvEAiUW+qUVKXvTJkVSzhK1aptgwLemUmxxNz72eqnkXgWTNv6W7J'
    'oaHBsydgQrtLBeOEtwYj/V6xnNXlyWVOw5SdY0QXMqYlF0rb69JZquyTKHvH2JrXd/y7gu84MmeF'
    'w1k9rnRRwY8cxBONbj+rSHklLnrSWbvkGPKB6TFba5pyxFPjIMxanJepgl4sStp7KhCrg8I6H4Hh'
    'oIa5koEWxLztyFPM22c+5RKCwDLPTfiad64Wn8+1Qdrm7VifclB9yj1BOuntatJm//uGFlZ4+hsB'
    'KKRZ7QBCC5ahaP1lRLXhMmLa8B9of47I8Fu0/4KgKOMDj9VdYXVXWL1aJ7UGtM7mMq5qnaEyktpr'
    'UH30pR/gKv8jdA0GH0QHAXXjPHoIqhfX0Mc10Y97BDSNATzEIJ4QzhqlVxF8x2tIQTio4FsFTQpm'
    'FM6MIOcdBepfSMMK2h//j0A3od+mryY/AQOkwku0pr3C1X18+oIX4Ycd8h+S+J7/IM8/+Irjh4o/'
    'kRcgnaOe8pwpe4VRAv8Z0d+QXmm7c4B7b4b+9G6TK21fHODBm6F9fPkWM/OUTPIbuLGPDGnUP7/G'
    'kxfHCeuiby9tMaQY7k3GMMqOGMMd1nTNr18g1hKtBiYi3pzzVA0V0H0AXqh9hxhDWoAFfnkK4B2+'
    'rvuuDeRII+TOQyKPjn8BUEsHCF5RCEQmBAAAIQgAAFBLAwQUAAgICACSujFdAAAAAAAAAAAAAAAA'
    'HAAAAG9yZy9pajJhcnQvSmF2YUNhbGxzJDEuY2xhc3N1Ustu01AQPTdJ7SR1WwNpG1oeKTU04VFD'
    'eGxASElwq4TEQXEKQl3AjW0lTo2NbKd8EmtAQgihfgBbfoNvQMxNK8KiteyZe47HM2dm/PPP9yMA'
    'D3A/jxTSMjIK5iAxrPDAiULP0SeJ5+utOAz64YEbMEiH3J+4McN6ubLfPj3qcQ5Z5GTkFcxDoWRh'
    'NNS9cZVHid7ih7zBfT/W7jFsaNYHL7FHHf5eO0mliVTafwVT+80caVtUsASVQakbu03zTbfeMhp9'
    'huJZEkQ/5xVcQIFBDiPHC7jPkC5XmjJWGNbGpEP3eTDUzdCa2KMdz/UdI4rCSFQrKrgoqs0fV6v1'
    'erXXgl9XcEnwktXvNc1dQV1RcHVKmXudutET1IaCa4KS691u26iZgtMUXBdcxtxrt2VsMagzCd3B'
    '2LUThuwT2/cCL3k6VfqSohuh4zIstb3ANSfvBm7U5wOfmAUr4fYBze0E561wEtnujifA4r8hb4sa'
    '9L0R2H4Ye8Gw4yaj0JFBwy+cthUacDMI3Kjh8zh2Y7VEm7xBfwhTi2KX4kRMGRXyNwn9QppOgPsN'
    '7OhH/gvkz+Je+Ipzme5HZJ5P4SrBuRlcIyjN4GWC8gyWCGZncJOgehz9CRJyKGAVyyhik4QtYwtV'
    'PCT/CDU8I2/gBSzyfbyFTT6FWyRPmor8jdtkS1BeyfSmc4oxhaGW7lBcCtvQyWdwl2yVnvy0ebrU'
    '7F9QSwcIBZy9sRwCAAA5AwAAUEsDBBQACAgIAJK6MV0AAAAAAAAAAAAAAAAeAAAAb3JnL2lqMmFy'
    'dC9KYXZhQ2FsbHMkQXJnLmNsYXNzbVDBSsNAEH2bNk0bYxNr1dqz0DaKEfFWESQgKEUPld43dQkJ'
    'a1I2ScHP8lAED36Av+C/iJMICtbD7psZ3ryZN++fr28AztA3oaFmoG5BR4PBifmSe5InoXcXxGKe'
    'MzTOoyTKLxhqw9GshSZaBkwLG7AYeqkKvSg+5Sr3bqjT51JmB5cqZKjnTwvB0Jn8Kk5zFSXhuNRo'
    'W7DhMOhLLos/tO/BY4bBcL15nTea0TA/fSAVexIl4rZ4DIS654GkijlNCzUXV1GZtH9WPC5VGKzr'
    'JBHKlzzLRGagx9D9zxBZJ0s4ob01upoGp3RPkVOaIGT0dGwRdigalCcltN0XMPdwBcM9WmHzuSJu'
    '09+oGj6I1q3kdrBLaFK1iT3so/8FUEsHCMrL6PkdAQAAnwEAAFBLAwQUAAgICACSujFdAAAAAAAA'
    'AAAAAAAAHwAAAG9yZy9pajJhcnQvSmF2YUNhbGxzJENhbGwuY2xhc3OdUctKw0AUPZMmjdZYY32m'
    '9f1C4yMi7hRRCoJSdFFx42pax5gSE5jE+l0uguDCD/Ar1A8R7xTRhdWFm3vmHuacc7n3+f3xCcA2'
    'lgrQkDOhWzCQZ7BbvM29kEe+d9poiWbKkN8NoiDdY8gtr5z3oge9JgoW+mAxOLH0vaC1xWXqHZOy'
    'ysMwWVCVwYjvIiEZSrVvz3oqg8jfUS5FCwPKIn8j0uv4UlGDFkqK6pGiKYK2kIoctjCiSD3hbaGI'
    'MQvjcIjg0k8YKhe1rkMcSH+H4Wr5Z/r/mD9iVs5pmmp8KRgGakEkTm5vGkKe8UZITKEe38qmOAxU'
    'U/wSbqgABusooiVVQ54kIjExyzDcLUb5E5pYYBj/bQ66EFVs0o40Oq4BWx2JXrbadAdLnzjyibRI'
    'Qtb5XSas0Guf1HnCGfcBzF3NYLprGfrd9Qy26+gZhlzHyDB631FOUC0iR/UFOl4xjTfST1KvYYo6'
    'UKZGE81gjhLmCRdR/gBQSwcIL0sYBXQBAAB/AgAAUEsDBBQACAgIAJK6MV0AAAAAAAAAAAAAAAAe'
    'AAAAb3JnL2lqMmFydC9KYXZhQ2FsbHMkSm9iLmNsYXNzrVd5fFTVFf7uLHkzk5eFkSlMRBxalEkw'
    'CSKmOtEUiEEnTqIQIiXYwmPyCA8n78U3MwG07ti61g1tQa2KxYjaVikZg1TsYrHa3e7W7i1tba1d'
    'bUut6Xdf1kkmyB+d32/evffcs99zzzn3pbefOQhgkfAH4IJbgUeFF0UC5Zu0Xq02pZldtRes36Qn'
    'MwJFZxmmkWkQcEcrL/LDB7+CgIpiqAIzLbur1ti0ULMztc2kbNRSqfTcZmu9gMvoFBDNkqBURZnE'
    '9nbqW+KdEjJNRRDHkXfK0jp1W2BGYkxwY0pLpxPORr1EDql4F2aQPCm5C8xakygoVn4dgrCKChwv'
    '4OnWDJNKdEjgCSpm40RySWe0jE5oXMEcgeMkq01py6xtbrugdcjmACJw+1Asx5NUnIx5NL4nS19U'
    'Rcfp2ZaxDbOrvrkyUYBHvQ+VtI8WrzVocgTzVZyCairV2p5ICAQTEz1dH0AtFig4VcVCnCZQOoaQ'
    'sMwunk3GajfTRpepdw6JFghFKX2SRlLv06XedQL1BTSeLHoqE86gCZmNtq51+lDhQz39YOqbfZit'
    'oCEvWIY4+7CYBMvbm9qbzvFhqYCyor21Nd56rg/nCPjb2hsbm5rOkXvLiLdsSTwh5+cRz9bT2VQm'
    'LQ+qWcV5OF9ger5OS2xb20qVWgSmDWOvzdhZM8nTdGLqAhUXylP3j0KlH1ZIP7QVPrmOwmZLZu0q'
    'LsIqKrZBM1JZm/ESmsJFqxlSum1bdgBrcLGCD6j4INbmOWel40GBkmTWtnUzM7KeHh1/eEPQegUa'
    'LXTA2YyRqj1PS29s0XoCWCfvKamCk90SQBJuKb9LxUYYVLZLzzRaZkbfkhl3mwTCeRLHXzRJfYmK'
    'FLpJnS5MXRGdgljmBQs9Ci5VYYNXNDzlBaW3rM2m5BYsFLhZ9CrYrGILttI/hbgIBLRkUk+n5y5Y'
    'sEDgrKPHd56WE+H1UuvLVXwIV/BeanYXmR8/RXJZYnfxaK4SKJvAxI9rcK2C61Rsk5YXzoikpoTM'
    '1h5don9YxUdkKvD2aqmsLo2+UcVNuHnMtFOlacsmubvAzU2MRQqjJM/G0XC2cKuKj0rtirr1zEar'
    'U4q8XcUduHNM5EIpcvlRRQ67d80knPFSbX1DimJrWxxJPNLtuFvBPSo+ho/TPVMhCqiM2Rar09hg'
    '6HbaqTbxAHbiXgX3qbgfn2D8FSAeJhDwGek2ZnYjSUdH45Ud0uwHVTwkzfbZelI3enXbh4cFmtIO'
    'XsQpJxGr28hERvbrI4bJXTOpD+/a+qVZw9ZHEWKXU3KspqbmCunD3SoeQd+YD0+TPjyjQESOd1A8'
    'ldK7tBRDItvNZNC0Jan3ZAzLrC/GHjym4HEVT+BTzBZ5J0uH0D8CJ0cLZe8CteRKfEbFk3iK2hnp'
    '+LBVsmIUoO9Q8FnW4IlqL80aKV6cAPbKcpgTmDfihoiRjpjZVCpi2RHTykQ0c8xx1oaIpBhQsR/P'
    'MOS0nh7d5PlWv4Nf8mQ6BnxOxbM4yCRMy1u1bn1ixhzNGnvxeRVfkKi+jDUElXH3JRXP48v0JPPZ'
    'EueEjPUpXcZHR+VFEuEFFV/Bi9TRMHutS7hzZgHvrDkmh8tw+6qKr8lw86S1Xl2e5jdk8fnmhJDI'
    'u7jveIzb8W0VL+M7tIJeWKFnsra5knmEncvkXO4k0O+p+D5+MBaUi2RQ1kfjx5BMCtdDyfRHKl7B'
    'j8eYni6ZhqMF8SvXLJUF6SfS+J8KRAtGbMHa/nPmRMNkzyQr9y8l/a8KV+74VA3Lbxgt8kaz+iv4'
    'LZ2UV1+tzRoDQNrzexWv4Q9j9tRJe6rznDSKP4Vb5AG/ruJPsm32JlO6Ziv4M8vaGIcVWdPUnIg7'
    'M9rcPEVVOlozyzBlNDVanWRRljBMvTXbvV63Vw4x9W1gY57eqHc6ybKDEcIEmLyEyWIEIW1qPemN'
    'FtPGzOgUzQ5dMJqB0gr+k+ey0R1KYFOl4G0mkIJmKGyoEZxcGRThIscCV4hy26ysndSXGVLV0lHL'
    'ayQqq0HcZJfgMNFlNXDeFJ6hDsLN3IkF7NJcFPoG/CiXrxG+Z8rlO8MZ2f9D/vjKcEY+IPhdLJ8A'
    'zpodpjOyyXPGCx18D/9e/IVc/8rZErgpA5hT9TRE1Yn9UKrm9KOkKuztR3lVuKgf06tCSj9mPkUk'
    'gb/xW0oSoJuMTEawxfnf8Y9hdqc66hKnah9meR+C4umDx/0EIS6HtsjZ7cGbjhIudbFc/hP/4jbJ'
    'RZQIUr/tkvzsA4isfhrvDr6HKyWHucEoJyX+7Tvh34uqPgTkcgA1OSwKvpfzmTvgC57ZB28wJkFn'
    'Kc/i7NXu4PvaVnuCS9pWe4ONbauLgk1tsxZyu/X4HaiRKlZWB88lcVySJDhpzWH5Ko4rD6G0Ovh+'
    'OePWquonR404macB9oBepOnxDF8yWaxFL9PBFvaWW3E1LsOdbLjedHzvHSQBu1qf4HtRQUTB2YM0'
    'cxjiHoIocA3yRCeiiclob2E55/i3c5ICR/h/y3Er/eedTZ0YC67rqzz9mDWAjoRocTccwDr6cX3M'
    'U3UASc70fsTddV53XdH8HDa0eBrm08jyHDaFvJxMP7hLpOQY8i6MKWFlH0y5PYBMzCdXlx18FlfG'
    '/GE/R1cs4K4rDhVzsQuxsJ8ziREqXrgPVw9TtYUDEoGwsb3rw54B3NC2rVj0DT4fdtjeEvYP4LZY'
    'cbg4h7sGsKNODakS/sALw0H0APzBXQP45HMjUNGHsrDHWe3Hoy7ESkLqTlSHSw6hhDxLcvj0Tsw+'
    'gL00eV+wP4enw74cDnDM4TmHUbEnhy+Gi8Ml4UAOh2KlktdLhxAc4vpSuHQ/vu7GqpBXKvWtcOkA'
    'vhsrC5cN4IcH68pDRaHyddMieBgzZPiEy3J4dZUDrCvqw1x5Aq1yYySKfxby5vCL4K8pc7lE3eYV'
    'fW/ffgJjdv4p9H0fZsQUGWwv8PJQojKA3/VjZdizH39kfRDyIgp5J4dwFC99wts5qw87STdG8H9g'
    'GI9Ny+MSHMcleIxcwtOee4pHtEfs5e5hzOPsdRwWR1xuV9HQ2tXAC/86IRxdi11xVwKHXQ2cNYxe'
    'tJexiN+rGNRXQ74pinEtSnAdE902zMH1mMcnxim4ATW4EXV8XCzGzYjjFqa7W7Gej4FNuE0+Agi5'
    'gz3sbWw578Iz7Daex91sH+7Bq+zX32THHsAOcRJ2ivm4V9ThPtGC+8UaNuNJPCCuxYPiYdwk9mC3'
    '2ItHxIt4VLyCPeI1PEaLdok32G0fwW6XG4+4KhiG87HHVY/HaMVuV5ywdYRdStg1hG3D4zIpiM2I'
    'DFJhhXdbwRoF/xUKOTIVSqg6AarAUnClgkFFSJQjaBjESSg5CpaC7axUYpC+e0c0lxC+4vOdvBLi'
    't+ItzOPwXyxikiGHSAElvb6lCg4fdzE3pIhJCC6ZspqIEjpGvEEEEJwkZuRHBCCP09FxHbaDjJnJ'
    'mtNat/P1CC/HCqf2ZUURZxZHheM1HH2o+B9QSwcI/ZcTVDcKAAA8FAAAUEsDBBQACAgIAJK6MV0A'
    'AAAAAAAAAAAAAAAmAAAAb3JnL2lqMmFydC9KYXZhQ2FsbHMkTnVtYmVyVG9rZW4uY2xhc3NtUMFK'
    'w0AQfZPWpE1jW2vrwZOIh7ZCI+JN8RIQlKKHSu+buoSNcQObVPwtD6XgwQ/wQ/wMcTaICnrZmXlv'
    '5u28eft4eQVwgh0fDmoe6gE24BK6qXgUYSZ0Et7EqVyUBPdMaVWeE2rD0byJBpoe/AAtBIS93CSh'
    'So+FKcMrnoxElhUH18uHWJrb/F5qQr2UT6zSm/4oz0qjdHJKGAz/oqM5z0T5nSR0pkrLLzERZ4z4'
    's3xpFvJC2aL9/ePEqhCCS62liTJRFLLw0Cf0/9uP0Pq1IY7YksPHYPPWVJWBr7HJsc3ZPrOW98dr'
    '0PhwBe+56unw61a978x3OTrYQs92MtrANgbY/QRQSwcI47ekmQUBAABpAQAAUEsDBBQACAgIAJK6'
    'MV0AAAAAAAAAAAAAAAAaAAAAb3JnL2lqMmFydC9KYXZhQ2FsbHMuY2xhc3Olewl8VNX1/zl3tpfJ'
    'y0LCBIYQGFazsskaENk1mEQlCAbchuSFDExm4syERWtditZqbWu12lCriEpaqzWiDUFaUNtKpbZW'
    '7W53u9dqF9u6gPl9z32TSSaZYPv/h8/Me/e+e88599yzfM99w4n3nzpKRHMdU72kyOEhp0kucjON'
    'jsa2zgxtmxOMJWauDe4IrgyGw3EmlxWLRWNMVaU1tdvQPTMcjGydub41Ft0Z3BK2FpfVyrxt8Whk'
    '5tqG8+vP37LNakosFtqGSVnkZXLuDMUsJn9pxpFlm1fIYNOkHMplcseseEc4wbQ4jd/KcDAeXzyo'
    'o3/2iNzzTRpFBUyeUGRHMBxqZlpYOmh+QyIWimzF/IGumnDY2hoML49t7WizIonVu5qs9kQoGtHk'
    'RpvkoyLI12YlWqOgdmHp6cRLkt88bMxghjGrJQxxZ9ZpkprNWJP8NA5SN0UjO6wY9LDmtHySC7Z7'
    'OhKh8My6YHsak0EqGW9SCU3AhiR2t2NDlmTQx1BetdFgsxVLI2jL4KUATfLQZJOm0FSm/KEMoakl'
    'oUgosZTJUVq2IQvsp5t0BpXK2sLROJgx8SYPlTNNHLYHDYlgwkptgEGVTGPFJgPWLqupIxGNBULx'
    'QJKMl8pohogxk8mXaYs189kmzaEzsfa1569oYMoborFsmkfzPbTApIW0iCkn7SlmxUNXWXolNQYt'
    'Zpo7e35Ay7MtuiUQD0cT8UC0qamjPWQ1Lw7I3ECzFQ4EA03RtvawlbCaZaBBZzFNEzMNtHXEE3gY'
    'SQRDkcDsGTPOXLRoTuCi9WuqFga27E5Y8Sw6m5Z5aLlJK2gl0yQtTiQUndnUGozFrQTWFow0B2PN'
    'K+22+CmmX76QaVztsMHJQdiz1bTGQ+eYdC7VQKMjDWTyRqydq6ymKPaeaUpp2Yg0k4MWZ9F5VOuh'
    'OpPq6XymycPHR5uxGasllixvkk2FgaxbfcH569YzTc1AfuhwCH8hrfNQg0nr6aJ+mxlZIphkNFIX'
    'DLdEY21Wc02kvQPLOqf0v+H0wasVWTaadLEI4otGLoq0BdvbJRrKuGBTwop5aRNt9tAlJl1KlzEV'
    'piiuwPau6GhpEQmdO2NiXP7SzSsG8RwYoflcYVKQtkBbzZo5U2VpxrGDKIgUKQrNZHmoxaSt1DpY'
    'joExTEYiavsKkkBp2XAPktixzaTtFIaZtYsmmGZl8rTNtZlyyFT5BpEIRT3UbtKVBJ6jYL+xaKh5'
    'ZjQ+szYabRc5crZaiTp4RH/bB2GGDVtsEHZy/PL29kCbeI/dK/EgEk0EYlawebeHdsC6M4qyNrpF'
    'osEuk3bTVVBqxNqVqEE057Ve6qAPSRi5hmlR6dq1I0TC0y1xk4SaDrrWpOuEuAo1e+kG+oiH9ph0'
    'I93ElDtAszYq6vYgNXVY57dgZ0rXDta8PNZB6WaTPka3IPRoA05LYWmxPz0pDuvy0MeZCgYp81zc'
    'h8VOb6VPyKo/yVRUmkHbZRtkyO0mfZrugMW2R+MQY8xgMdZ1RCI2Ethk0GeYJgzelpgl7BH/dLRs'
    'gpY8dHdaugCSwJ556S7qFDn2jkh9g4y5x6TP071MWeKNQatN4oizdJP9cJ9J90sycsUT2B0PPdBv'
    '8OmQRdT6kEkHqEvDjbboDtjz9AyaHSGNftGkh+lL4NsSisB0SmTnRjK2xWJWj5r0ZXoMfhaPBNvj'
    'rVFocCxkzghdPPQ4NirtyfJYLLjbS900SSR/0qSvUA8k16YTF1Jlg5LZymhYMIXEsWzqpcMeesqk'
    'I/RVuHamQRAqhHAVTAjEK0qjVJPsB52jdMxDT5v0DD0L4YYPgSG3BuP18CWdIzfJjG+Y9E16DlqK'
    '6O70wJLSZjd9Swz8eabSjBswXBHQ0Lexrxl056UTNMmg70KaGGJlrDkuPd8T+i8Jnjwt2vkAPNlB'
    'r5j0fVm+gV0PxVutZoN+yLQ0hQIQgK7ssDqs5pkxmKxQD4SQ44MRCUtbLLlrsqD2ZmT4FEQw6DqR'
    '8Sci40+ZyjPIuDazSAb9DOsECUEXQuMXQuOXmWmMYGsSrH5t0m8kWLmarV01zWJgvzXpd9qLmsJW'
    'MCY9fzDpj+IsDsRnD/0ZHjqUw4qOULhZosmfZAf+CpjTEdkeie6MpFDS5aHmAMJCohV6ao9Fm6x4'
    'vDog49806W/0d9gzUqgl/lT1ATA9jeNiIfFPIfEWkkJ6DB0+0DLoP1gY3NbaJTp7R3T2bmad1Yyk'
    '9xIvnaL3PdRnMklOzRuSKJiyoaf1gNj1wTYLAYOVyQ52whWawiHk+zMycxvWZzCqMpd28yw6wYbJ'
    'WSzlVP1FtbVwwwxBns200GrT8XI255qcJ7jWHbYiWxOtBo9CCE3AUJuC2nwCAAk8Gll5YPKKaBT7'
    'H/FwUVreEsTh4bFpy25ojSLc8ri0+TWRhLXVinl4fNrYNeFoEGMnpAm6KtqBuOzhQFpvfUfbFtgU'
    'T+TJJk9hmGR2sx64QVSiI80qL5fwdJPP4FLZ13h9sF7ywaqyTfKg3OQKeeANxWsi4rYielVaUkgB'
    'NoNnapPHBkIdPNvkOYxywcBWJne1sDRTFXSK55k8X+zAg6Gy4wYDhbuj7UGEAw9XM1UMr/hqIjui'
    'UD0C8PpgDPNSpY6X9vMSk8/ipUnewQ5BW2PSeA8U3wYvA+M2OFNwqyVzV5i8UoTxCpSyuw1eDUP1'
    '8jl8rodrTF7L56XtaF0wgQmOthCSgau0pqasRiymzuR6BpJ3CwRenhCt1pSt9HIlX2jyOpYSKhQ/'
    'N7S1taED0HkrzEiGrBTFZ/NFJm/gjZKlO7bEk8iySEhnwpYnyJI5m0zezJfYqxYjg8YnZILryVqm'
    'bPMKg4Gsx+h6KmLFE6CG8rDJsprjgdnzs/gKDnp4i8lNjKBSlDFBz0ZpNbVhZyjR1Ioyb2oS/UyV'
    '3DZ1LRx/fXS7Ba2ozVBJC2/1cKvJId4Grv1ASadBGbrOCuqqw9luWdtRhQ2CrqkxmtxiL4e5zcMR'
    'k6PikkWZh2FbkcFCkWBYWF9pckxicvYWa2sokkx33ELH5GGHyTtkzw3JtHbMOcG7TN7NiOsOJOYR'
    '6uJNBn8I/Js72sMhiQMBrcqWkBVultCs+MMmX8vXYU2C0JhmlA5fkr3s9PDVnzQh2g0mf0TkzkJk'
    'T0nNN5p8k/R69WpseIPum03+mHQbGJzqvNXkj2uDlsXZknv4E0yBjBtqhwytQC/fRjOEwu0mf1oS'
    'd7ZQSEY1LxfynQDl/BkxzE2DpU+O0OLfbfJntURasx3hsMHApz5rV7sNaoO2ynSIFoXdY/Ln5Rgi'
    'r6nVatqeii1xD9/Xj79gyvYqbM15+V5byv0AvyyANblTGJfULbAtnj9k8gEBvl4Yf60VCVmRRBYM'
    '6Qsmf5EfZjJX16+6fNX5Ky+qW12PinrsSMZn8CNYQCIWDIXFX7T4cg4BcsLlyyY/lsz90bgOKI+b'
    'fJCfQG0WbG5u6GhvjyGoWM2COjOfBm4w+CsagCH6xROilEMm9/JhCYnJg6HFpy9iUik/Y/rlIyKd'
    'bLbQ/prJR/kYaGurhaFXZD5k3JyB/gZxk2dMfpa/Dv0h6qQg5hAwmlkgG4wCwXKuwcC507RQw092'
    '5gTsE0Nd/MASvoWCf8QS0sMn+pOo3rhzg/HWBgtb8zxNElbfARLj74o/Z/I4g78nIAN0DPIZ/Aoa'
    'yC5xg38AEwYktkI7JNH9SM6zgju0xf7E5J/yq1Bgf5henFmB/w0kA/+fo5JeItH8lyb/SsKPV5di'
    '8Y0hAR2/AfloJLw7qZF4IBizAnEYFeCDHJxFoqI5SNLRhKIiHpBjPiTtUDAcugpeJPv1W1HA74aU'
    'axkkGijX+A8m/5H/hBiE5GvFLKBwpnkjmqBWe4OVyLy+vyCyJ6LRQFsw0r+KQDu8HLfazf860rnD'
    '8thWg9/ENgSTp8si2d9N/gf/E76lD6gRgZPAZup/IR2Cwuv8Lwka/86MKDPUNhuy+W1+x8Pvmvwe'
    'n0w75WyQUz8HfHxIruifilzxPh4N5AoxoEAEC0eq4OOKIIlippbTS/I/9Ixw0AJFSpBRDqD2DqT9'
    'pmA7ArE4XCwaDjT1h1ypNXRws+3aUC7sTAfiXAw4J6gPJOSpPd9QHqSBWbPnnDl33vwFCxcFtzQ1'
    'Wy3LV6xctXoNjFllmcqrsvWrBBQOclojYKjGUDlMxcnXCza9iyIhOaRL0c3Djk++ZOaWlkgsYSiA'
    '7sK04fYwB9H7fYYC/B6T9nRnKwBrvD3YBHxUqYpMNUZglxGK11oJQazKL0f5sQ6BT6rYVONlT90I'
    'vMFw3FBA2K4W3EGKgFThkr3UZKYyTTusq/7+eIXyVOhUBvQE8Ts9nP9oqGkwCzgOLEedYapSYWEk'
    'wxuYlKNcw1ObilhDIBgJoGoMh7AFYiLNgZiV6IhF7BxZHTBUJVSd4ppMoNEkNMhWM0w1U5K1JxRf'
    '3dae2G0oYLS5g8ZHohFLHiQ3NhBtCQQTgbYons+ZN3/AACRaqDNNNVeOPpzbrd2Qdj6ScKouHYR1'
    'DAXEzpsNBbC+AHjbLlqDEuAD8qokjiDV1BoIxmFVic2XVuqTxrUb6lDBx5tioXYJVoZaIkDxUlnE'
    'UlOdLcFPgIwOfdK53FQr1EqdGtvDQQlCq9Le7EDwBkmaiE+LR+rPFJMU0P24fhUsTErdHEKMiaOe'
    'iHvVOepcj6ox1Vp1Xlrl3l+LJFMe4NHOGgTfoA6Q04e/dcqM8bJVnanqBcgaQJqtK2H9hroAy9xi'
    '4yhDrYP+5aWGodbL0ZzUiobaIIkKSzPUxTAwqNVQm9AVjoqvXiKmK3WioS6Tg29d9BnqCgzYAUyT'
    'xYVqi6maFIKVc33jBVDAqGHSZrFPbcniMfJVKV9+fNENclcsXyVqi6HamCYLxf7T4+BAMJ+pS0G9'
    '/SjyVNRU7epKLKslGhOIzXRWpnOW/+H1mVJxUyVUB5a/JbprSNAf/q6wf9oJtdNUuxQ2LAuQpf/Y'
    '/oPSYarYOqWuNtWHNBwOxS+IhdqQXnfoFX7YVNeKd+ti2TYDQ10PKCT+HRLTl5dZqFmxFwGUTK0D'
    'utJaghd9BNBGAsegU6/2oMDFQCIaEB43muqmpHdrqzPUzQBOtskOUBPsGALO7I8OQfv885S6xVS3'
    'SlGeL4UxhEEoiOiDFjHy20z1CfVJaFO/wMp0mliTKSVKaL0dlYD6tGDalWVDXE/HEhjTbepOU31G'
    '3SURV59nFmRyxc8y1YXsc4/TrCeii5RAqRh7AAE3Ggg2SfkvA5qtplBbMJyMbmUetbe/cGhDmT5z'
    'RWjrKnuEV3XSDFef/Xdd8uY6ctkXIpd8yZ8reb02eXNtn8u+9PW5rk3OBzH1qCjhy/I2qv8QbQjH'
    'xTKq21SPq4MwPm0MMWt9VL/YzzheMuST2K1+jUQ7EvFQsxiKHF8HYlCdJTR7TXVYPcWUKwrREGj1'
    'rmCTfZS81gs//qqI9jWpjVakVWoIKohAY9Qxef60nDE3pBm9hBoM8KtnZcDX9RlE2gt/WzAMKVbf'
    'NNVz6jjMX7/f0qdUI5TNa2T48yZXqBMCBNbIkUexesHkM9QJQwGcT9KxK5Wz7IMnJEZ9AGqvGhO+'
    'JzK9JEKvGSyT5gyJStQrpvq+AnLP1hLZR2QjiLTKUAD1k+1AeXrGJeonwvinQmnVYMY2Axjxz+AI'
    'OltncHlD/YJpyuJkwo73m7aGCwIbrkawqJ4xY8Y14q6/MtWvFTD/qK36zWkY5tJcl/z1xLIMy/if'
    'fizhUb9N++FAfbQBOdp+OOg07ZT6van+IFJk6RMxeSy9fzLVnyWUyCtHlLVWTId7j3q9/931aX8R'
    '4lV/oRke9WZ/PtUQujYU2W41S8VWF2z3qjdoEtJYQ+356wHauAasVkZ1XE1oEwfoo3xI1RDaCjza'
    'IT+QGfIrjiVDXweO/JJp6WJY4kr9djgPYljJY5Cgthh3vGMLwvzAcdqw9LR284pNZWshYUMi2LQd'
    'rPVMjzrFNP507zvhLSmVxD0OSjtZTT2BFgBfYrvldHFt2eYVkuZDcX2iaLeaY9F2kEqVZ3F5tLYM'
    'eGDp8N8ALSlf+l+/tvE4vADopykkTvdCtb8sWjLcUJcibzDV/D9OHd7pceRCdRnOKJjO/v/4jY6o'
    'asi7jVT/CIOjGQd/0O+NMqxz+JSlGV9LOwqRSoc7PtPGD5JkpKAxdHVD4gYMTbJtPD511qxZA43Z'
    'gxtzBjfOHNyYO7gxb3BjvjSMJU3h5I+evA3RjliTtSYkLpibMrsZIhiTWROJWDEtrzZ3eYZ8B19G'
    'vB90iIk+2CnNJkUBBAwnjVN/V/8gVv9ES6m3aJz8qgntf+n2v8krv2vAvVd+aoXrJMycQlMx4j9o'
    'lcBFWTBB+SGa+DhuWL2Nb7fuLKYy9Y56F2QwlO+R3+7hygdpWiflHKGyxoKKQ1R17CDNOkxzkdbz'
    '7092V0t31dFOyq46Oirvsw9SVsGSXsrDyKU9tOogre2hC/T3hqpeauyhy3uoqdrld/VSqNrtc3ZS'
    'Vi+1dZGTqz3SKvB7jicpx4XyEepoPEg7L/EGn6CdE8v9mHKIrq42IIjfeJI+3EvX+43D9FEHbZTp'
    'E47QrY1+zyG6zW/00Kf20hRN6k6b1F2NfuMQfbY6y5/l7KHP+bN66L4u8ldnDaJ2mB5UtNGfdUx3'
    'PArlPEK/od/RfqhG1LWBfPieSvk0DVqeTtX4Xglt11EZXUzldDlVUBtV0vVURQBpmD2LHscevkDz'
    '6Ec0n35OC0BvCSguoj9g9tu0mN6js9R7oDqNsvOLTNcpmunhbI86ucxDkZPk099rPdThW+Gh/T71'
    'vjYGVn1U5mCHsvcMIuEOV3NCL30By3uklzzdQ3Z5edpch8OZnHs1OUhy0jlHqLvxEB08T+/zE0yH'
    '6RBTbcVhAgDrpHG4AZB6mjrqyisdYNFDxzd29b12hE5g1gsF3ynvoReTbG1t5Wqyq8mgNVj7OXqV'
    'uaROUZGHuj109F2amCaSK7WcMPpkbrUsp66yh17em7SLHyQNcUJqt/r5/2hCD/244FUs/udpUhSA'
    'FtF5QMO1VISdmkL1WhKD+KRI0pEmg9vhSXpMC/pk5sI0ddRVJtUxubJfHfVVT9KvJty5l8wqLajL'
    '+UhX36uOR1ISePXWrIMOGjRnkxwnKRcKmAqXozJ+jJ5N8rwSGyVjFzufoGlpfM8rT/L1l/fzra2w'
    '2TnA7rd68GuIJ48MWfhGfF8ME2yEyW0aYF8A9sXC3iu/aEmy35y0hKqUgn+v9IZXHqdxR+hP0PNf'
    'Cl7voTeg6n/00L/E1SuH7vdl8A7xgysGtFwBLYNRjozQIeZbEMqNq9m/ef8e10NvF7yHFZ0cxdTL'
    'DFuqB9fcqkJ2HWQPmt2Vz3B2J82qfJqzq53S73eOUsmxG/3OHs5B80HsQiHnixVs7KJHK5+hGxBX'
    'ZHRlDxfIyC66G5QK99JYXHx7aRQuY/aSFxd/J+XZQ/W4KLqK7SclnTQTjCf28KRFmvdYZy9P20vZ'
    'ci3rxBhQRyBLzpyHKZXD+E5Ecwaas3p4bmqVhbxAC1s1oMc1NArfjyFmdyOWPI4ofxCb9wTV0JN0'
    'KX2FtlIP7aBD9GnqpXthHo/QU+g9Qj+gr9Iv6Wv0Bj3NXnpW6/8yyjlJlR46MUv5irNz+mg8udhD'
    'pzwUQKeDFL4Rb/qwHZn7Kb3fYfej+S65fcUDvmPnIYeBfXZJwNEGdU/Sh+oqnuFFUG5FDy9+jgy5'
    '1Ca3vq5yYPPTNbOxspDPRufygV2GhuthcIB2dA6tTYXlcWJM9BwV0nE8eR7B9gSefxtO/4JWgo8c'
    'hX1wPwdWsh8LILnKi3EHO5OSWknTn1t+nDyFvKq7HPZU3Mtrzhovd/tpzPh7qbB8vLO5h2t7+YJO'
    'cu9RfeWO8T28fmiseRFW/z3s4UvIAi9rATykjJP6vafOrTbLKfA+icvZYHCxZExuHBqyfwAZr+Xr'
    'kom5HZoV+r8ozs9/kLyFfKnOtXw5CFg9vH3Gw3adf0yoaBqkkcAOfO7F5wFtVUSH+lWPee34xDtp'
    'IS6J+sqqHt7ZScVJVy/kq+HrCGpv9Pt6VXmx84pevkbvRd9xTLq+sjuZNoTaHptaQWVqnKSIv6L3'
    'o5Wi0Vu6j/BtjXJziD8pHZ/q5Tvkehd8vLuQO4VLSpt2tv0L4sbrtAxWfS69iRj+N2qgvyOk/YN2'
    '0T/pRnqLbqZ/0cfp3/QJeofuondpL3JqN52Et5yCp/TRESjjODO9yIp+hJz5nk6YOTlzThIM+YTE'
    'J85+l/LeJZfu6fbhzpnt8QzKDF75Day9D44gNjEfQuaW9/LnjnBL4xG+t7H8EO87xPfXITXyg5UO'
    'LL4Wrm4d5K6HZKu+pPXXw492ka/evkoUk7DVXXWsopCf7OWeukrn1zi7Ecj4qYZe/irs/6kefroe'
    'u/KNTsku/I38gN74bwo1aX+Nj1c7j/DzjYf429Uux3y3zy3d+zlW5XP38AuF/CLoVnv8HiNJeUZD'
    'o7OQX2podBXyyw2N7kL+fkMjLP6HwtGPmxm9/ONqQ+5ekjvApUL+WQ//olMY/1oYy7Pva0spTN6+'
    'BkjHv9dAzitdL+unucnbp7vImzSS6mx/NuQbRX16HX/W5LL1Ql6vNh3zc3w5urmf1vmzfTl6BW/I'
    'CnL9uS69goL39AJcWtxc3IB7dZ4/TyT4m9/05Rzh1xv9uQXvQXh/3iF+q2FPDnf1PSyy/HBArB/i'
    'sZY3x5/zHJX6Xf6cw/wfBdsZn7L+U7B8f86A+fudPvcRPg4c6c/ye/05fvMQ9zXscXPX+7f6nd3y'
    'X0WA9xYgtCwExjs7FZ5uoclwSAPcvDSas8nPJk3kHJrFubQAfTWcRxcysiaPoq1cQB/mQvooj6ZP'
    'sY/u4SJ6mMfQSzyWfsd++g+PYx8X81wez2u4hC/gCXwpT+QwB/g6nsS38GS+nafwAfQ/wtP4mzyd'
    '3+QzlIt9KpvLtO3fT6NP0SyJ6Nwigd8B8yfc67DYh2DlTHZIlNQhs09wiR32CU5VJUmAut3v02gA'
    'VQ+/ze9TUzIxcPa4Zfg6SWPwvQajTlIhvk+R6XFk8bt0sc9+XKGzSzG5bbI2RZsaXGuQ48nvKuyI'
    'qSYlYUOLY4kjGZf5knKE4NqlJfmT91E+srXHiW11LOnis4o76ZqS/MB+GJpSsn8l+Zfs4+l7FOup'
    '+6TfKf2awnynz5nfsY/mOea7fC7PfirrH3gfjSpUbj2oRxn3yDRTpu1xwa5+BH8uVLk+Z/+jfHnU'
    'Rcc0Z19JftZ9lFeSDyJZJfle8CwpVAWadaEtkqWfrN5Hk5FgJiQTTP6s+6mg/37RA+TuokhJfvB+'
    'GXrVg0Jw+f10SUn+pgdow/j5zvHOK+wkVYQ5V0iCUj7UVlhAV9/vy31O3bleCq9CNbZHjdtLAbkt'
    '0bc+uZ2obyHVJL0yTHx//+OpQBwDaiCeSYpnkcmzqYDn0DQ+E9B1Ls3nebSE51M9L6CLeCFdwovI'
    '4moY8WK6Efef4LNoHy+lB3gZPcvL6XleQX/nlfQWr2KTV3MezLiSz+EFfC5fzDV8Oc9ii+u0oc6m'
    'safgNUCQxbyMHfljTlE+8wQ3wjOq1VFqjNudPSEbxoSdeofmoBvm8g/+p40yKQKPlHx5ZvkzdAL6'
    'KK9AkNqIRncnTSp/mrrrHEtLKnW0KagsQazB87/tcUBprw+svUiO0fkCyuEL4bzr4LwNNIcv0vLl'
    'kCPnFOXAcPkdKhqGhbIhzR/5T0lprk5m7xXlhWrK4GCvptrBXk1FTKqvqDqspkscSmVhVZaehQch'
    'RVu4jWTwxVTEjTSBN9Ey3qyFyyY+Jf+TSLxymGgmROvlw0kkUpOsHqeKogY4A42/UagqBjhDZycG'
    'mOuyhi9DKLtcM3QQTwTZn/KrySouIf/LUArPcqC41+ps/D5O8HuPqtpL+foOqJ2B2tN5zhqEOTBo'
    'CMDiLeTmJsCpZliepXlnkQK+QhwZMyh03CK/EEou8TuQJQvXbeU9ak6qiLssWcRxdr1jvrNCPOTo'
    'fLdjvsfn8bn300S/y+eZU21U+Q34ByzIOR/RJWuPBybyK59z8B7NS9+jrr77BkxoMvAgcSuAdIhy'
    'eRuN5e0w6DDifhu1cIRCHNWLKCP3SXKhMOtDmDVk5xywraPYP8YdAAyNf5tc79B4qdpKaIJtWCrb'
    'Btl8FwxrQTJRq0V6vwrV4h51lg3vcqQFZNujlqHRbENItUqPc8hzF6LN+opeKnb0qjXA4t3ldWpp'
    'ZY+q/ZINK18VPXf/5+qXcD1KfPebuH6KZgSxOGqiGXdswPV6mvPch3C9jxZceCeu33W8GhYIut71'
    'vcmX4Ppl94175HkM5n6+1ul1jqVddDWaF+rmlU40w2g26OYWF5qXonmRbja40axHc6NurvKgeTaa'
    'jbo5z0BzFpqbdXN6vowOoH2pbhfly/B8tC/XbXe+sbQkCZk32xfZKJorRT8+S/BZhs8qfM7Fpxaf'
    'C2QtB1Ww+6Cy8GnBZys+rfiE8NmGz/buQhW2tVrRqyIDtruU8rBLMRrFcWx/ghZxB13AO7mVdyF9'
    '7+Z2vooTfDVaH8K/a5DOP8x7AP9vxt0n+XptIhNpzKgzik7RZjGKXP2Xl2fOdST/3MMcPY+88qo5'
    '6ZH3J0uOxnKs4YAUOoXduLX0rU9uW/TtGLndqm8r5bZV3/rlNnSA3AU3yN023Vkst9v1bUl3+cBq'
    'p4u78Y2UzTchNH2UJvHNVMkfA+C5hZbzrVTLH6eNfJtelZeMbC/+srzepNj56POjrtMW7jwDYc5E'
    '9yvlvSpWX6Gj+TmVFYhGCJo9aoc+p6itOE458O6rEFkArqsqetQ1neSq6E756HXwTxj63AE3rUDZ'
    'cYDOkFn6+DA58IZhAxlFitoDAwTzbp0oP6rnI4lUO/HoYxI6BMx/A75TbUcQ3dxPJX437vHQ50GK'
    'qeylMb3q4zqE/NLv7q7CFhwgE/VxoRYW7coDNKnCjpUVdoR07kPpjFuHTu2fkkG+h2gMLmMeonxc'
    '/A9RVlXBDQc4FxNv66QcjL7tSXVHF42Vbhpl0/MKEY16nX7ncVnF3bKKI6qz0e88pD5X7RLKByhr'
    'tLoHniP0dePeLioULrqxr4vco9X+Be7U2AcHjz0weOwX9NiHFxh+V5G7Vz3Sox77HOWjYdiNe2lq'
    'SulPDCi9UH1lEOp29ahDC7w2t+wi782396oj3TY/ad7Rq4522xy9aPaqZ7qLvL10vfQVo/bCpeQA'
    'bbEVszmpGH2AVIyt9zt71TcWusa4etW39lK2XL+tA+h3hLc0X+yWMS8vco1FhVEmRz64TtNjfihj'
    '0FQ/7hYFwy7sfczJYHyvDl7ezweWl3KYHqqCw9yOLPFpgKw7qITvpHn8GYSIu+Eon6Xd3ElX8+fo'
    'Br4HlcHn6S6+F9XBffQF3ofK9n56mR+g3/CD9B4/xB7g/8ncxWfyF3gtf5E38MMc5C8huDzCt/Gj'
    'ePJlPsyP8SvczW/x4/weH1RefkL5+Ul1Bn9FVfEhtYJ71Xl8WK3jp1QjH1Ht/FW1g4+qa/iYupOf'
    'Vnv5WXWQv64d+CYq1ad8pzw8rpRH98Fzjf5Do3n6pttuIvi8S1PeJpU3dVx+oV0J5CTLBdVpmiuc'
    'JynXaV+LnYGT5HPm5vQJchpMDshLihDgGreu2Ysc7nfIlZM1LPqNQhjxASXZCOxJoBEPrnPKK5DW'
    'ftldr6+/sz34j+LBz9EYv8t+WO0Ww0NvV9+fq45pHOMmj3oNKSKX8nAdL29XcB0c7o6javoW0Njz'
    'lMcnEOi/TeP5BQCV79B03M/iF7W2Ksl1DijZlZboLNvjKBDSjK9T5ME3umtxeZcGoNtryTWNxppG'
    'AQjZuGaSwC5JzEfUXxrLD6m/DjlC4lfyDYcPWMFOABOSSM9dLol+6HHTuAEFYlYRdtGeNTF5OOaB'
    'whC/Tj9tDPSdaVrhyNNew7SxqSUNvKqCfwybhKF+eYuQzmGccMg+vWDjUidvgzkMe00iHIpTJ5gp'
    'hY2DwnjYWDIc41Pv2Cr0SKK8I+qNxkPqb0/QLO8TtHPgbZv9IqAEV5B1lOjtnOCYiGs53P44WgGQ'
    'RLJ2TKJxfIXQyjf4NrQno/06rlNo3P8BUEsHCEDdAFpTIwAAxkMAAFBLAQIUABQACAgIAJK6MV0A'
    'AAAAAgAAAAAAAAAJAAQAAAAAAAAAAAAAAAAAAABNRVRBLUlORi/+ygAAUEsBAhQAFAAICAgAkrox'
    'XTirBf06AAAAOQAAABQAAAAAAAAAAAAAAAAAPQAAAE1FVEEtSU5GL01BTklGRVNULk1GUEsBAgoA'
    'CgAACAAAYBAxXQAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAuQAAAG9yZy9QSwECCgAKAAAIAABg'
    'EDFdAAAAAAAAAAAAAAAACwAAAAAAAAAAAAAAAADbAAAAb3JnL2lqMmFydC9QSwECFAAUAAgICACS'
    'ujFdE90zfyYEAABXFwAAFwAAAAAAAAAAAAAAAAAEAQAAb3JnL2lqMmFydC9CYWNrdXAuY2xhc3NQ'
    'SwECFAAUAAgICACSujFdQ806iwgFAADzCAAAIAAAAAAAAAAAAAAAAABvBQAAb3JnL2lqMmFydC9C'
    'cmlkZ2UkQ2FsbFBsYW4uY2xhc3NQSwECFAAUAAgICACSujFd+onUiUIOAADfHAAAFwAAAAAAAAAA'
    'AAAAAADFCgAAb3JnL2lqMmFydC9CcmlkZ2UuY2xhc3NQSwECFAAUAAgICACSujFdXlEIRCYEAAAh'
    'CAAAHAAAAAAAAAAAAAAAAABMGQAAb3JnL2lqMmFydC9Ib29rQ29udGV4dC5jbGFzc1BLAQIUABQA'
    'CAgIAJK6MV0FnL2xHAIAADkDAAAcAAAAAAAAAAAAAAAAALwdAABvcmcvaWoyYXJ0L0phdmFDYWxs'
    'cyQxLmNsYXNzUEsBAhQAFAAICAgAkroxXcrL6PkdAQAAnwEAAB4AAAAAAAAAAAAAAAAAIiAAAG9y'
    'Zy9pajJhcnQvSmF2YUNhbGxzJEFyZy5jbGFzc1BLAQIUABQACAgIAJK6MV0vSxgFdAEAAH8CAAAf'
    'AAAAAAAAAAAAAAAAAIshAABvcmcvaWoyYXJ0L0phdmFDYWxscyRDYWxsLmNsYXNzUEsBAhQAFAAI'
    'CAgAkroxXf2XE1Q3CgAAPBQAAB4AAAAAAAAAAAAAAAAATCMAAG9yZy9pajJhcnQvSmF2YUNhbGxz'
    'JEpvYi5jbGFzc1BLAQIUABQACAgIAJK6MV3jt6SZBQEAAGkBAAAmAAAAAAAAAAAAAAAAAM8tAABv'
    'cmcvaWoyYXJ0L0phdmFDYWxscyROdW1iZXJUb2tlbi5jbGFzc1BLAQIUABQACAgIAJK6MV1A3QBa'
    'UyMAAMZDAAAaAAAAAAAAAAAAAAAAACgvAABvcmcvaWoyYXJ0L0phdmFDYWxscy5jbGFzc1BLBQYA'
    'AAAADgAOANUDAADDUgAAAAA='
)
# END_EMBEDDED_HOOK_API_JAR

TEMPLATE = '''package {package};

import android.util.Log;

import org.ij2art.HookContext;

/**
 * ij2art ART-hook replacement. The install command is:
 *
 *   ij2art ctl --pid PID hook add --dex-id DEX_ID \\
 *       --target 'com.target.Class.method(I)Ljava/lang/String;' \\
 *       --replacement '{binary}.{method}(Lorg/ij2art/HookContext;)Ljava/lang/Object;'
 *
 * The replacement method MUST be `public static Object name(org.ij2art.HookContext)`
 * and live inside the uploaded DEX (it is resolved against that DEX's own
 * InMemoryDexClassLoader). Constructors cannot be replacements.
 *
 * HookContext contract (see out/ij2art-hook-api.jar):
 *   ctx.executable   the hooked Method or Constructor (reflection object).
 *   ctx.method / ctx.constructor
 *                    the same target; exactly one is non-null.
 *   ctx.thisObject   receiver for instance methods; for constructor targets the
 *                    already-allocated object being initialized; null for static.
 *   ctx.args         boxed arguments; primitives arrive as their wrapper types.
 *   ctx.callOriginal()
 *                    runs the original implementation with ctx.args and returns its
 *                    (boxed) result. For a constructor it initializes ctx.thisObject
 *                    in place and returns null; it never allocates a second object.
 *   ctx.callOriginal(newArgs)
 *                    same, with replacement arguments (count/types must match).
 *
 * Semantics to keep in mind:
 *   - The context is confined to the calling thread and this invocation; do not
 *     store it. A `hook update` does not invalidate an in-flight invocation.
 *   - For a synchronized target, ART holds the receiver/declaring-class monitor
 *     around the ENTIRE replacement, including callOriginal -- keep it fast.
 *   - The return value must match the target's return type (boxed); for void and
 *     constructor targets return null. Throwing propagates to the original caller.
 *   - Coverage is ENTRY_ONLY: callers that already inlined the target bypass the
 *     hook. A hook that "never fires" on a hot path is usually this, not a bug.
 *   - This DEX is loaded with parent-first delegation, so android.* and
 *     org.ij2art.HookContext resolve from the app/SDK loaders -- do not bundle
 *     the Hook SDK classes into the output (the build script already keeps them
 *     on the compile-only classpath).
 */
public final class {className} {{
    private static final String TAG = "{tag}";

    private {className}() {{}}

    public static Object {method}(HookContext ctx) throws Throwable {{
        Log.i(TAG, "enter " + ctx.executable + " args="
                + java.util.Arrays.deepToString(ctx.args));
        Object result = ctx.callOriginal();
        Log.i(TAG, "exit " + ctx.executable + " -> " + result);
        return result;
    }}
}}
'''


def fail(message):
    raise RuntimeError(message)


def find_binary(directory, name):
    candidate = directory / 'bin' / name
    if directory and candidate.is_file():
        return str(candidate)
    found = shutil.which(name)
    return found


def resolve_jdk(flag):
    """Return (javac, jar) from --jdk, JAVA_HOME or PATH."""
    home = Path(flag).expanduser() if flag else (
        Path(os.environ['JAVA_HOME']).expanduser() if os.environ.get('JAVA_HOME') else None)
    if home:
        javac, jar = find_binary(home, 'javac'), find_binary(home, 'jar')
        if not javac or not jar:
            fail(f'JDK at {home} has no bin/javac and bin/jar')
        return javac, jar
    javac, jar = shutil.which('javac'), shutil.which('jar')
    if not javac or not jar:
        fail('no JDK found: pass --jdk DIR, set JAVA_HOME, or put javac/jar on PATH')
    return javac, jar


def resolve_sdk(flag):
    if flag:
        sdk = Path(flag).expanduser()
    else:
        for env in ('ANDROID_HOME', 'ANDROID_SDK_ROOT'):
            if os.environ.get(env):
                sdk = Path(os.environ[env]).expanduser()
                break
        else:
            usable = lambda p: (p / 'platforms').is_dir()
            sdk = next((p for p in (Path('~/Library/Android/sdk').expanduser(),
                                    Path('~/Android/sdk').expanduser(),
                                    Path('~/android-sdk').expanduser()) if usable(p)), None)
            if sdk is None:
                fail('no Android SDK found: pass --sdk DIR or set ANDROID_HOME')
    if not sdk.is_dir():
        fail(f'Android SDK directory does not exist: {sdk}')
    return sdk


def version_key(path):
    return [int(part) if part.isdigit() else -1 for part in re.split(r'[.-]', path.name)]


def resolve_build_tools(sdk, flag):
    root = Path(flag).expanduser() if flag else sdk / 'build-tools'
    if (root / 'd8').is_file():
        return str(root / 'd8')
    if root.is_dir():
        versions = sorted((p for p in root.iterdir() if (p / 'd8').is_file()),
                          key=version_key, reverse=True)
        if versions:
            return str(versions[0] / 'd8')
    fail(f'no d8 found: pass --build-tools DIR or install SDK build-tools under {sdk}/build-tools')


def resolve_platform(sdk, flag):
    if flag:
        given = Path(flag).expanduser()
        if given.is_file():
            return str(given)
        candidate = given if given.is_dir() else sdk / 'platforms' / flag
        if (candidate / 'android.jar').is_file():
            return str(candidate / 'android.jar')
        fail(f'--platform {flag}: no android.jar found')
    root = sdk / 'platforms'
    versions = sorted((p for p in root.iterdir() if (p / 'android.jar').is_file()),
                      key=version_key, reverse=True) if root.is_dir() else []
    if not versions:
        fail(f'no SDK platform with android.jar under {root}: pass --platform')
    return str(versions[0] / 'android.jar')


def embedded_hook_api(work):
    """The self-contained fallback: materialize the JAR embedded above into `work`."""
    if not _EMBEDDED_HOOK_API_JAR_SHA256:
        return None
    data = base64.b64decode(_EMBEDDED_HOOK_API_JAR_B64)
    if hashlib.sha256(data).hexdigest() != _EMBEDDED_HOOK_API_JAR_SHA256:
        fail('the embedded ij2art-hook-api.jar is corrupt (sha256 mismatch); '
             're-download this script or pass --hook-api JAR')
    path = Path(work) / 'ij2art-hook-api.jar'
    path.write_bytes(data)
    return str(path)


def resolve_hook_api(flag, work):
    if flag:
        given = Path(flag).expanduser()
        if not given.is_file():
            fail(f'--hook-api JAR not found: {given}')
        return str(given)
    for candidate in (REPO / 'out' / 'ij2art-hook-api.jar',
                      Path(__file__).resolve().parent / 'ij2art-hook-api.jar',
                      Path('ij2art-hook-api.jar')):
        if candidate.is_file():
            return str(candidate)
    embedded = embedded_hook_api(work)
    if embedded:
        return embedded
    fail('no ij2art-hook-api.jar found: it is required to compile against org.ij2art.HookContext; '
         'pass --hook-api JAR, run ./build.sh, or use a script with the embedded copy')


def read_manifest(project):
    path = project / MANIFEST
    if not path.is_file():
        fail(f'{path} missing: run init first, or pass --class/--method')
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as e:
        fail(f'{path}: invalid JSON: {e}')
    if not CLASS_RE.match(data.get('class', '')) or not METHOD_RE.match(data.get('method', '')):
        fail(f'{path}: invalid class/method names')
    return data['class'], data['method']


def cmd_init(args):
    if not CLASS_RE.match(args.class_name):
        fail(f'--class must be a qualified Java class name, got: {args.class_name}')
    if not METHOD_RE.match(args.method):
        fail(f'--method must be a Java identifier, got: {args.method}')
    project = Path(args.directory)
    package, class_name = args.class_name.rsplit('.', 1)
    source = project / 'src' / Path(*package.split('.')) / (class_name + '.java')
    if source.exists() and not args.force:
        fail(f'{source} already exists (use --force to overwrite)')
    source.parent.mkdir(parents=True, exist_ok=True)
    tag = 'ij2art.' + class_name[:16]
    source.write_text(TEMPLATE.format(package=package, className=class_name,
                                      binary=args.class_name, method=args.method, tag=tag))
    (project / MANIFEST).write_text(json.dumps(
        {'class': args.class_name, 'method': args.method}, indent=2) + '\n')
    emit(args, {'project': str(project), 'source': str(source),
                'next': f'python3 {Path(__file__).name} build {project}'})


def cmd_build(args):
    project = Path(args.directory)
    class_name, method = read_manifest(project)
    if args.class_name:
        class_name = args.class_name
    if args.method:
        method = args.method
    sources = sorted((project / 'src').rglob('*.java'))
    if not sources:
        fail(f'no .java sources under {project}/src')
    javac, jar = resolve_jdk(args.jdk)
    sdk = resolve_sdk(args.sdk)
    d8 = resolve_build_tools(sdk, args.build_tools)
    android_jar = resolve_platform(sdk, args.platform)
    out_dex = Path(args.output) if args.output else project / 'out' / 'replacement.dex'
    with tempfile.TemporaryDirectory(prefix='hookproj-') as tmp:
        hook_api = resolve_hook_api(args.hook_api, tmp)
        classes = Path(tmp) / 'classes'
        classes.mkdir()
        run([javac, '--release', '8', '-Xlint:-options',
             '-cp', os.pathsep.join([hook_api, android_jar]),
             '-d', str(classes)] + [str(s) for s in sources])
        archive = Path(tmp) / 'replacement.jar'
        run([jar, 'cf', str(archive), '-C', str(classes), '.'])
        dex_dir = Path(tmp) / 'dex'
        dex_dir.mkdir()
        run([d8, '--min-api', '31', '--lib', android_jar,
             '--classpath', hook_api, '--output', str(dex_dir), str(archive)])
        out_dex.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(dex_dir / 'classes.dex', out_dex)
    replacement = f'{class_name}.{method}{SIGNATURE}'
    remote = f'/data/local/tmp/{out_dex.name}'
    commands = [
        f'adb push {out_dex} {remote}',
        f'ij2art ctl --pid PID dex upload {remote}',
        "ij2art ctl --pid PID hook add --dex-id DEX_ID "
        f"--target 'com.target.Class.method(I)V' --replacement '{replacement}'",
    ]
    emit(args, {'dex': str(out_dex), 'replacement': replacement, 'commands': commands})


def run(command):
    print('+', ' '.join(command), file=sys.stderr)
    try:
        subprocess.run(command, check=True)
    except subprocess.CalledProcessError as e:
        fail(f'command failed with exit {e.returncode}: {command[0]}')
    except FileNotFoundError:
        fail(f'tool not found: {command[0]}')


def emit(args, data):
    if getattr(args, 'json', False):
        print(json.dumps({'ok': True, 'data': data}))
    else:
        for key, value in data.items():
            if isinstance(value, list):
                print(f'{key}:')
                for line in value:
                    print(' ', line)
            else:
                print(f'{key}: {value}')


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0],
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='action', required=True)
    for name, handler in (('init', cmd_init), ('build', cmd_build)):
        p = sub.add_parser(name)
        p.add_argument('directory', help='project directory')
        p.add_argument('--json', action='store_true', help='print a machine-readable envelope')
        p.set_defaults(handler=handler)
    sub.choices['init'].add_argument('--class', dest='class_name',
                                     default='com.example.hooks.SampleHook',
                                     help='qualified replacement class name')
    sub.choices['init'].add_argument('--method', default='onHook',
                                     help='replacement method name')
    sub.choices['init'].add_argument('--force', action='store_true')
    build = sub.choices['build']
    build.add_argument('--jdk', help='JDK home (default: JAVA_HOME or PATH)')
    build.add_argument('--sdk', help='Android SDK root (default: ANDROID_HOME or common paths)')
    build.add_argument('--build-tools', help='build-tools directory containing d8')
    build.add_argument('--platform', help='android-36, a platforms dir, or an android.jar path')
    build.add_argument('--hook-api', help='path to ij2art-hook-api.jar')
    build.add_argument('--class', dest='class_name', help='override manifest class')
    build.add_argument('--method', help='override manifest method')
    build.add_argument('-o', '--output', help='output .dex path')
    args = parser.parse_args()
    try:
        args.handler(args)
    except RuntimeError as e:
        if getattr(args, 'json', False):
            print(json.dumps({'ok': False, 'error': {'code': None, 'message': str(e)}}))
        else:
            print(f'error: {e}', file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
